# Input geometry type. Possible values:
#   OCC: IGES / STEP format
#   STL: STL format
#   CSG: Constructive solid geometry
#   Geom2D: Netgen 2D spline geometry
geotype: OCC

# Output mesh type. Possible values:
#   VOL: Netgen native format
#   Neutral: Neutral format
#   Surface: Surface Mesh format
#   DIFFPACK: DIFFPACK format
#   TecPlot: TecPlot format
#   Tochnog: Tochnog format
#   Abaqus: Abaqus format
#   Fluent: Fluent format
#   Permas: Permas format
#   FEAP: FEAP format
#   Elmer: Elmer format
#   STL: STL format
#   STL_ext: STL Extended format
#   VRML: VRML format
#   Gmsh: Gmsh format
#   Gmsh2: Gmsh2 format
#   OpenFOAM: OpenFOAM 1.5+ format
#   OpenFOAM_compressed: OpenFOAM 1.5+ compressed
#   JCMwave: JCMwave format
#   TET: TET format
meshtype: VOL

# Global upper bound for mesh size.
maxh: 1000

# Mesh grading how fast the local mesh size can change.
grading: 0.3

# Load meshsize from file. Can set local mesh size for points and along edges. File must have the format:
#   nr_points
#   x1, y1, z1, meshsize
#   x2, y2, z2, meshsize
#   ...
#   xn, yn, zn, meshsize
#
#   nr_edges
#   x11, y11, z11, x12, y12, z12, meshsize
#   ...
#   xn1, yn1, zn1, xn2, yn2, zn2, meshsize
meshsize:

# Minimal number of segments per edge.
segmentsperedge: 1

# Quad-dominated surface meshing.
quad_dominated: no

# Do fast blockfilling.
blockfill: yes

# Block fill up to distance.
filldist: 0.1

# Use delaunay meshing.
delaunay: yes

# 3d optimization strategy:
#   m: move nodes
#   M: move nodes, cheap functional
#   s: swap faces
#   c: combine elements
#   d: divide elements
opt3d: cmdmustm

# Number of 3d optimization steps.
optsteps3d: 3

# 2d optimization strategy:
#   s: swap, opt 6 lines/node
#   S: swap, optimal elements
#   m: move nodes
#   p: plot, no pause
#   P: plot, pause
#   c: combine
opt2d: smcmSmcmSmcm

# Number of 2d optimization steps.
optsteps2d: 3

# Weight of element size w.r.t. element shape in optimization.
elsizeweight: 0.2

# [OCC / STL specific parameter] Factor for meshing close edges.
closeedgefac: 2

# [OCC / STL specific parameter] Minimum edge length to be used for dividing edges to mesh points.
minedgelen: 0.001

# [STL specific parameter] Angle for edge detection.
yangle: 30

# [STL specific parameter] Edges continue if angle > contyangle.
contyangle: 20

# [STL specific parameter] Angle of geometry edge at which the mesher should set a point.
edgecornerangle: 60
